package models

var AWSCores = []byte(
	`{
"MachineType" :[
			{"instanceType":"t1.micro","cores": 1 },
			{"instanceType":"t2.nano","cores": 1},
			{"instanceType":"t2.micro","cores": 1},
			{"instanceType":"t2.small","cores":1},
			{"instanceType":"t2.medium","cores": 2 },
			{"instanceType":"t2.large","cores": 2},
			{"instanceType":"t2.xlarge","cores":4},
			{"instanceType":"t2.2xlarge","cores": 8 },
			{"instanceType":"t3.nano","cores": 1},
			{"instanceType":"t3.micro","cores":1},
			{"instanceType":"t3.small","cores": 1 },
			{"instanceType":"t3.medium","cores": 1},
			{"instanceType":"t3.large","cores":1},
			{"instanceType":"t3.xlarge","cores": 2 },
			{"instanceType":"t3.2xlarge","cores": 4},
			{"instanceType":"a1.medium","cores":1},
			{"instanceType":"a1.large","cores": 2 },
			{"instanceType":"a1.xlarge","cores": 4},
			{"instanceType":"a1.2xlarge","cores":8},
			{"instanceType":"a1.4xlarge","cores": 16 },
			{"instanceType":"m1.small","cores": 1},
			{"instanceType":"m1.medium","cores":1},
			{"instanceType":"m1.large","cores": 1 },
			{"instanceType":"m1.xlarge","cores": 4},
			{"instanceType":"m2.xlarge","cores": 2 },
			{"instanceType":"m2.2xlarge","cores": 4},
			{"instanceType":"m2.4xlarge","cores": 8},
			{"instanceType":"m3.medium","cores":1},
			{"instanceType":"m3.large","cores": 1 },
			{"instanceType":"m3.xlarge","cores": 2},
			{"instanceType":"m3.2xlarge","cores":4},
			{"instanceType":"m4.large","cores": 1 },
			{"instanceType":"m4.xlarge","cores": 2},
			{"instanceType":"m4.2xlarge","cores":4},
			{"instanceType":"m4.4xlarge","cores": 8 },
			{"instanceType":"m4.10xlarge","cores": 20},
			{"instanceType":"m4.16xlarge","cores":32},
			{"instanceType":"m5.large","cores": 1 },
			{"instanceType":"m5.xlarge","cores": 2},
			{"instanceType":"m5.2xlarge","cores":4},
			{"instanceType":"m5.4xlarge","cores": 8 },
			{"instanceType":"m5.12xlarge","cores": 24},
			{"instanceType":"m5.24xlarge","cores":48},
			{"instanceType":"m5d.large","cores": 1 },
			{"instanceType":"m5d.xlarge","cores": 2},
			{"instanceType":"m5d.2xlarge","cores":4},
			{"instanceType":"m5d.4xlarge","cores": 8 },
			{"instanceType":"m5d.12xlarge","cores": 24},
			{"instanceType":"m5d.24xlarge","cores": 48},
			{"instanceType":"c1.medium","cores": 2 },
			{"instanceType":"c1.xlarge","cores": 8},
			{"instanceType":"cc2.8xlarge","cores": 16},
			{"instanceType":"cg1.4xlarge","cores":8},
			{"instanceType":"cr1.8xlarge","cores": 16 },
			{"instanceType":"c3.large","cores": 1},
			{"instanceType":"c3.xlarge","cores":2},
			{"instanceType":"c3.2xlarge","cores": 4 },
			{"instanceType":"c3.4xlarge","cores": 8},
			{"instanceType":"c3.8xlarge","cores":16},
			{"instanceType":"c4.large","cores": 1 },
			{"instanceType":"c4.xlarge","cores": 2},
			{"instanceType":"c4.2xlarge","cores":4},
			{"instanceType":"c4.4xlarge","cores": 8 },
			{"instanceType":"c4.8xlarge","cores": 18},
			{"instanceType":"c5.large","cores":1},
			{"instanceType":"c5.xlarge","cores": 2 },
			{"instanceType":"c5.2xlarge","cores": 4},
			{"instanceType":"c5.4xlarge","cores":8},
			{"instanceType":"c5.9xlarge","cores": 18 },
			{"instanceType":"c5.18xlarge","cores": 36},
			{"instanceType":"c5d.large","cores":1},
			{"instanceType":"c5d.xlarge","cores": 2 },
			{"instanceType":"c5d.2xlarge","cores": 4},
			{"instanceType":"c5d.4xlarge","cores": 8 },
			{"instanceType":"c5d.9xlarge","cores": 18},
			{"instanceType":"c5d.18xlarge","cores": 36},
			{"instanceType": "h1.2xlarge","cores":4},
			{"instanceType":"h1.4xlarge","cores": 8 },
			{"instanceType":"h1.8xlarge","cores": 16},
			{"instanceType":"h1.16xlarge","cores":32},
			{"instanceType":"hi1.4xlarge","cores": 8 },
			{"instanceType":"hs1.8xlarge","cores": 8},
			{"instanceType":"g3.4xlarge","cores": 8},
			{"instanceType":"g3.8xlarge","cores": 16 },
			{"instanceType":"g3.16xlarge","cores": 32},
			{"instanceType":"g2.2xlarge","cores":16},
			{"instanceType":"x1.16xlarge","cores": 32 },
			{"instanceType":"x1.32xlarge","cores": 64},
			{"instanceType":"x1e.xlarge","cores":2},
			{"instanceType":"x1e.2xlarge","cores": 4 },
			{"instanceType":"x1e.4xlarge","cores": 8},
			{"instanceType":"x1e.8xlarge","cores":16},
			{"instanceType":"x1e.16xlarge","cores": 32 },
			{"instanceType":"x1e.32xlarge","cores": 64},
			{"instanceType":"r3.large","cores":1},
			{"instanceType":"r3.xlarge","cores": 2 },
			{"instanceType":"r3.2xlarge","cores": 4},
			{"instanceType":"r3.4xlarge","cores": 8},
			{"instanceType":"r3.8xlarge","cores": 16 },
			{"instanceType":"r4.large","cores": 1},
			{"instanceType":"r4.xlarge","cores": 2},
			{"instanceType":"r4.2xlarge","cores":4},
			{"instanceType":"r4.4xlarge","cores": 8 },
			{"instanceType":"r4.8xlarge","cores": 16},
			{"instanceType":"r4.16xlarge","cores":32},
			{"instanceType":"r5.large","cores": 1 },
			{"instanceType":"r5.xlarge","cores": 2},
			{"instanceType":"r5.2xlarge","cores":4},
			{"instanceType":"r5.4xlarge","cores": 8 },
			{"instanceType":"r5.12xlarge","cores": 24},
			{"instanceType":"r5.24xlarge","cores":48},
			{"instanceType":"r5d.large","cores": 1 },
			{"instanceType":"r5d.xlarge","cores": 2},
			{"instanceType":"r5d.2xlarge","cores":4},
			{"instanceType":"r5d.4xlarge","cores": 8 },
			{"instanceType":"r5d.12xlarge","cores": 24},
			{"instanceType":"r5d.24xlarge","cores":48},
			{"instanceType":"z1d.large","cores": 1 },
			{"instanceType":"z1d.xlarge","cores": 2},
			{"instanceType":"z1d.2xlarge","cores":4},
			{"instanceType":"z1d.3xlarge","cores": 6 },
			{"instanceType":"z1d.6xlarge","cores": 12},
			{"instanceType":"z1d.12xlarge","cores": 24 },
			{"instanceType":"p2.xlarge","cores": 2},
			{"instanceType":"p2.8xlarge","cores": 16},
			{"instanceType":"p2.16xlarge","cores":32},
			{"instanceType":"p3.2xlarge","cores": 4 },
			{"instanceType":"p3.8xlarge","cores": 16},
			{"instanceType":"p3.16xlarge","cores":32},
			{"instanceType":"i3.large","cores": 1 },
			{"instanceType":"i3.xlarge","cores": 2},
			{"instanceType":"i3.2xlarge","cores":4},
			{"instanceType":"i3.4xlarge","cores": 8 },
			{"instanceType":"i3.8xlarge","cores": 16},
			{"instanceType":"i3.16xlarge","cores":32},
			{"instanceType":"i2.xlarge","cores": 2 },
			{"instanceType":"i2.2xlarge","cores": 4},
			{"instanceType":"i2.4xlarge","cores":8},
			{"instanceType":"i2.8xlarge","cores": 16 },
			{"instanceType":"d2.xlarge","cores": 2},
			{"instanceType":"d2.2xlarge","cores":4},
			{"instanceType":"d2.4xlarge","cores": 8 },
			{"instanceType":"d2.8xlarge","cores": 18},
			{"instanceType":"db.t1.micro","cores":1},
			{"instanceType":"db.t2.micro","cores": 1 },
			{"instanceType":"db.t2.small","cores": 1},
			{"instanceType":"db.t2.medium","cores": 2},
			{"instanceType":"db.t2.large","cores": 2 },
			{"instanceType":"db.m1.small","cores": 1},
			{"instanceType":"db.m1.medium","cores": 1},
			{"instanceType":"db.m1.large","cores": 2},
			{"instanceType":"db.m1.xlarge","cores": 4 },
			{"instanceType":"db.m2.xlarge","cores": 2},
			{"instanceType":"db.m2.2xlarge","cores": 4},
			{"instanceType":"db.m2.4xlarge","cores": 8 },
			{"instanceType":"db.m3.medium","cores": 1},
			{"instanceType":"db.m3.large","cores":1},
			{"instanceType":"db.m3.xlarge","cores": 2 },
			{"instanceType":"db.m3.2xlarge","cores": 4},
			{"instanceType":"db.m4.large","cores":1},
			{"instanceType":"db.m4.xlarge","cores": 2 },
			{"instanceType":"db.m4.2xlarge","cores": 4},
			{"instanceType":"db.m4.4xlarge","cores":8},
			{"instanceType":"db.m4.10xlarge","cores": 20 },
			{"instanceType":"db.cr1.8xlarge","cores": 16},
			{"instanceType":"db.r3.large","cores": 1},
			{"instanceType":"db.r3.xlarge","cores": 2 },
			{"instanceType":"db.r3.2xlarge","cores": 4},
			{"instanceType":"db.r3.4xlarge","cores": 8},
			{"instanceType":"db.r3.8xlarge","cores": 16 }
	]}`)

var AzureCores = []byte(
	`{
"MachineType" :[
			{"instanceType":"Standard_B1ls1","cores": 1 },
			{"instanceType":"Standard_B1s","cores": 1},
			{"instanceType":"Standard_B1ms","cores": 1},
			{"instanceType":"Standard_B2s","cores":2},
			{"instanceType":"Standard_B2ms","cores": 2 },
			{"instanceType":"Standard_B4ms","cores": 4},
			{"instanceType":"Standard_B8ms","cores":8},
			{"instanceType":"Standard_B12ms","cores": 12 },
			{"instanceType":"Standard_B16ms","cores": 16},
			{"instanceType":"Standard_B20ms","cores":20},
			{"instanceType":"Standard_D2s_v3","cores": 2 },
			{"instanceType":"Standard_D4s_v3","cores": 4},
			{"instanceType":"Standard_D8s_v3","cores":8},
			{"instanceType":"Standard_D16s_v3","cores": 16 },
			{"instanceType":"Standard_D32s_v3","cores": 32},
			{"instanceType":"Standard_D48s_v3","cores": 48},
			{"instanceType":"Standard_D64s_v3","cores": 64 },
			{"instanceType":"Standard_D2as_v3",
			"cores": 2},
			{"instanceType":"Standard_D4as_v3","cores":4},
			{"instanceType":"Standard_D8as_v3","cores": 8 },
			{"instanceType":"Standard_D16as_v3","cores": 16},
			{"instanceType":"Standard_D32as_v3","cores":32},
			{"instanceType":"Standard_D48as_v3","cores": 48 },
			{"instanceType":"Standard_D64as_v3","cores": 64},
			{"instanceType":"Standard_D2_v3","cores": 2 },
			{"instanceType":"Standard_D4_v3","cores": 4},
			{"instanceType":"Standard_D8_v3","cores": 8},
			{"instanceType":"Standard_D16_v3","cores":16},
			{"instanceType":"Standard_D32_v3","cores": 32 },
			{"instanceType":"Standard_D48_v3","cores": 48},
			{"instanceType":"Standard_D64_v3","cores":64},
			{"instanceType":"Standard_D2a_v3","cores": 2 },
			{"instanceType":"Standard_D4a_v3","cores": 4},
			{"instanceType":"Standard_D8a_v3","cores":8},
			{"instanceType":"Standard_D16a_v3","cores": 16 },
			{"instanceType":"Standard_D32a_v3",
			"cores": 32},
			{"instanceType": "Standard_D48a_v3","cores":64},
			{"instanceType":"Standard_DS1_v2","cores": 1 },
			{"instanceType":"Standard_DS2_v2","cores": 2},
			{"instanceType":"Standard_DS3_v2","cores":4},
			{"instanceType":"Standard_DS4_v2","cores": 8 },
			{"instanceType":"Standard_DS5_v2","cores": 16},
			{"instanceType":"Standard_D1_v2","cores":1},
			{"instanceType":"Standard_D2_v2","cores": 2 },
			{"instanceType":"Standard_D3_v2","cores": 4},
			{"instanceType":"Standard_D4_v2","cores":8 },
			{"instanceType":"Standard_D5_v2","cores": 16 },
			{"instanceType":"Standard_A1_v2","cores": 1},
			{"instanceType":"Standard_A2_v2","cores": 2},
			{"instanceType":"Standard_A4_v2","cores": 4 },
			{"instanceType":"Standard_A8_v2","cores": 8},
			{"instanceType":"Standard_A2m_v2","cores": 2},
			{"instanceType":"Standard_A4m_v2","cores":4},
			{"instanceType":"Standard_A8m_v2","cores": 8 },
			{"instanceType":"Standard_DC2s","cores": 2},
			{"instanceType":"Standard_DC4s","cores":4},
			{"instanceType":"Standard_F2s_v2","cores": 2 },
			{"instanceType":"Standard_F4s_v2","cores": 4},
			{"instanceType":"Standard_F8s_v2","cores":8},
			{"instanceType":"Standard_F16s_v2","cores": 16 },
			{"instanceType":"Standard_F32s_v2","cores": 32},
			{"instanceType":"Standard_F48s_v2","cores":48},
			{"instanceType":"Standard_F64s_v2","cores": 64 },
			{"instanceType":"Standard_F72s_v22,3","cores": 72},
			{"instanceType":"Standard_E2s_v3","cores":2},
			{"instanceType":"Standard_E4s_v3 2","cores": 4 },
			{"instanceType":"Standard_E8s_v3 2","cores": 8},
			{"instanceType":"Standard_E16s_v3 2","cores":16},
			{"instanceType":"Standard_E20s_v3","cores": 20 },
			{"instanceType":"Standard_E32s_v3 2","cores": 32},
			{"instanceType":"Standard_E48s_v3 2","cores":48},
			{"instanceType":"Standard_E64s_v3 2","cores": 64 },
			{"instanceType":"Standard_E64is_v3 3","cores": 64},
			
			{"instanceType":"Standard_E2as_v3","cores": 2 },
			{"instanceType":"Standard_E4as_v3","cores": 4},
			{"instanceType":"Standard_E8as_v3","cores": 8},
			{"instanceType": "Standard_E16as_v3","cores":16},
			{"instanceType":"Standard_E32as_v3","cores": 32 },
			{"instanceType":"Standard_E48as_v3","cores": 48},
			{"instanceType":"Standard_E64as_v3","cores":64},
			{"instanceType":"Standard_E2_v3","cores": 2 },
			{"instanceType":"Standard_E4_v3","cores": 4},
			{"instanceType":"Standard_E8_v3","cores": 8},
			{"instanceType":"Standard_E16_v3","cores": 16 },
			{"instanceType":"Standard_E20_v3","cores": 20},
			{"instanceType":"Standard_E32_v3","cores":32},
			{"instanceType":"Standard_E48_v3","cores": 48 },
			{"instanceType":"Standard_E48_v3","cores": 64 },
			{"instanceType":"Standard_E64i_v3 2, 3","cores": 64},
			{"instanceType":"Standard_E2a_v3","cores":2},
			{"instanceType":"Standard_E4a_v3","cores": 4 },
			{"instanceType":"Standard_E8a_v3","cores": 8},
			{"instanceType":"Standard_E16a_v3","cores":16},
			{"instanceType":"Standard_E32a_v3","cores": 32 },
			{"instanceType":"Standard_E48a_v3","cores": 48},
			{"instanceType":"Standard_E64a_v3","cores":64},
			{"instanceType":"Standard_M208ms_v2 1, 2","cores": 208 },
			{"instanceType":"Standard_M208s_v2 1, 2","cores": 208},
			{"instanceType":"Standard_M8ms 3","cores": 8 },
			{"instanceType":"Standard_M16ms 3","cores": 16},
			{"instanceType":"Standard_M32ts","cores": 32},
			{"instanceType":"Standard_M32ls","cores":32},
			{"instanceType":"Standard_M32ms 3","cores": 32 },
			{"instanceType":"Standard_M64s","cores": 64},
			{"instanceType":"Standard_M64ls","cores":64},
			{"instanceType":"Standard_M64ms 3","cores": 64 },
			{"instanceType":"Standard_M128s 2","cores": 128},
			{"instanceType":"Standard_M128ms 2, 3, 4","cores":128},
			{"instanceType":"Standard_M64","cores": 64 },
			{"instanceType":"Standard_M64m","cores": 64},
			{"instanceType":"Standard_M128 2","cores":128},
			{"instanceType":"Standard_M128m 2","cores": 128 },
			{"instanceType":"Standard_DS11_v2 3","cores": 2},
			{"instanceType":"Standard_DS12_v2 3","cores":4},
			{"instanceType":"Standard_DS13_v2 3","cores": 8 },
			{"instanceType":"Standard_DS14_v2 3","cores": 16},
			{"instanceType":"Standard_DS15_v2 2","cores":20},
			{"instanceType":"Standard_D11_v2","cores": 2 },
			{"instanceType":"Standard_D12_v2","cores": 4},
			{"instanceType":"Standard_D13_v2","cores":8},
			{"instanceType":"Standard_D14_v2","cores": 16 },
			{"instanceType":"Standard_D15_v2 1","cores": 20},
			{"instanceType":"Standard_L8s_v2","cores": 8},
			{"instanceType":"Standard_L16s_v2","cores": 16},
			{"instanceType":"Standard_L32s_v2","cores": 32},
			{"instanceType":"Standard_L48s_v2","cores":48},
			{"instanceType":"Standard_L64s_v2","cores": 64 },
			{"instanceType":"Standard_L80s_v2 5","cores": 80},
			{"instanceType":"Standard_NC6","cores":6},
			{"instanceType":"Standard_NC12","cores": 12 },
			{"instanceType":"Standard_NC24","cores": 24},
			{"instanceType":"Standard_NC24r*","cores":24},
			{"instanceType":"Standard_NC6s_v2","cores": 6 },
			{"instanceType":"Standard_NC12s_v2","cores": 12},
			{"instanceType":"Standard_NC24s_v2","cores":24},
			{"instanceType":"Standard_NC24rs_v2*",	"cores": 24 },
			{"instanceType":"Standard_NC6s_v3",	"cores": 6},
			{"instanceType":"Standard_NC12s_v3","cores": 12},	
			{"instanceType":"Standard_NC24s_v3","cores": 24 },
			{"instanceType":"Standard_NC24rs_v3*","cores": 24},
			{"instanceType":"Standard_ND6s","cores":6},
			{"instanceType":"Standard_ND12s","cores": 12 },
			{"instanceType":"Standard_ND24s","cores": 24},
			{"instanceType":"Standard_ND24rs*","cores":24},
			{"instanceType":"Standard_NV6","cores": 6 },
			{"instanceType":"Standard_NV12","cores": 12},
			{"instanceType":"Standard_NV24","cores": 24},
			{"instanceType":"Standard_NV12s_v3","cores": 12 },
			{"instanceType":"Standard_NV24s_v3","cores": 24},
			{"instanceType":"Standard_NV48s_v3","cores": 48},
			{"instanceType":"Standard_HB60rs","cores": 60},
			{"instanceType":"Standard_HC44rs","cores": 44 },
			{"instanceType":"Standard_H8","cores": 8},
			{"instanceType":"Standard_H16","cores": 16},
			{"instanceType":"Standard_H8m","cores": 8 },
			{"instanceType":"Standard_H16m","cores": 16},
			{"instanceType":"Standard_H16r 1","cores":16},
			{"instanceType":"Standard_H16mr 1","cores": 16 }
			]
}`)

var GCPCores = []byte(
	`{
"MachineType" :[
			{"instanceType":"n1-standard-1","cores": 1 },
			{"instanceType":"n1-standard-2","cores": 2},
			{"instanceType":"n1-standard-4","cores": 4},
			{"instanceType":"n1-standard-8","cores":8},
			{"instanceType":"n1-standard-16","cores": 16 },
			{"instanceType":"n1-standard-32","cores": 32},
			{"instanceType":"n1-standard-64","cores":64},
			{"instanceType":"n1-standard-96","cores": 96 },
			{"instanceType":"n1-highmem-2","cores": 2},
			{"instanceType":"n1-highmem-4","cores":4},
			{"instanceType":"n1-highmem-8","cores": 8 },
			{"instanceType":"n1-highmem-16","cores": 16},
			{"instanceType":"n1-highmem-32","cores":32},
			{"instanceType":"n1-highmem-64","cores": 64 },
			{"instanceType":"n1-highmem-96","cores": 96},
			{"instanceType":"n1-highcpu-2","cores": 48},
			{"instanceType":"n1-highcpu-4","cores": 64 },
			{"instanceType":"n1-highcpu-8","cores": 8},
			{"instanceType":"n1-highcpu-16","cores":16},
			{"instanceType":"n1-highcpu-32","cores": 32 },
			{"instanceType":"n1-highcpu-64","cores": 64},
			{"instanceType":"n1-highcpu-96","cores":96},
			{"instanceType":"n2-standard-2","cores": 2 },
			{"instanceType":"n2-standard-4","cores": 4},
			{"instanceType":"n2-standard-8","cores": 8 },
			{"instanceType":"n2-standard-16","cores": 16},
			{"instanceType":"n2-standard-32","cores": 32},
			{"instanceType":"n2-standard-48","cores":48},
			{"instanceType":"n2-standard-64","cores": 64 },
			{"instanceType":"n2-standard-80","cores": 80},
			{"instanceType":"n2-highmem-2","cores": 2 },
			{"instanceType":"n2-highmem-4",	"cores": 4},
			{"instanceType":"n2-highmem-8",	"cores":8},
			{"instanceType":"n2-highmem-16","cores": 16 },
			{"instanceType":"n2-highmem-32","cores": 32},
			{"instanceType": "n2-highmem-48","cores":48},
			{"instanceType":"n2-highmem-64","cores": 64 },
			{"instanceType":"n2-highmem-80","cores": 80},
			{"instanceType":"n2-highcpu-2","cores":2},
			{"instanceType":"n2-highcpu-4","cores": 4},
			{"instanceType":"n2-highcpu-8","cores": 8},
			{"instanceType":"n2-highcpu-16","cores":16},
			{"instanceType":"n2-highcpu-32","cores": 32 },
			{"instanceType":"n2-highcpu-48","cores": 48},
			{"instanceType":"n2-highcpu-64","cores":64 },
			{"instanceType":"n2-highcpu-80","cores": 80 },
			{"instanceType":"m1-ultramem-40","cores": 40},
			{"instanceType":"m1-ultramem-80","cores": 80},
			{"instanceType":"m1-ultramem-160","cores": 160 },
			{"instanceType":"m1-megamem-96","cores": 96},
			{"instanceType":"m2-ultramem-208 3","cores": 208},
			{"instanceType":"m2-ultramem-416 3","cores":416},
			{"instanceType":"c2-standard-4","cores": 4 },
			{"instanceType":"c2-standard-8","cores": 8},
			{"instanceType":"c2-standard-16","cores":16},
			{"instanceType":"c2-standard-30","cores": 30 },
			{"instanceType":"c2-standard-60","cores": 60},
			{"instanceType":"f1-micro","cores":0.2},
			{"instanceType":"g1-small","cores": 0.5 }
]
}`)
